=======================================================================
                             gh-repo-prune
=======================================================================
-----------------------------------------------------------------------
                Prune dead branches from a github repo
-----------------------------------------------------------------------

Overview
========

gh-repo-prune outputs a list of commands which, when run, will
delete from a repository at github.com all branches which
are not backing any open pull request.

See the top of the script for a list of exceptions.

The script uses the Github HTTP API to assemble the lists
of branches and pull requests, and emits commands which assume
`git(1)` and SSH access to github.com.

Synopsis
========

::

  gh-repo-prune <oauth-token> <account>/<repo> | sh


Install
=======

::

  npm install -g coffee-script
  git clone https://github.com/roman-neuhauser/gh-repo-prune.git


Use
===

#. Create a new *Personal API Access Token*
   at https://github.com/settings/applications.
#. Run `gh-repo-prune` and store its output in a file: ::

    .../gh-repo-prune <oauth-token> <account>/<repo> > output

#. Review said output to verify that you're not going to
   remove branches you didn't mean to!
   The output includes commented-out git branch commands
   to recreate dropped branches.
#. Run it: ::

    sh output

Done!
